### ISSUE TITLE
Saving changes in Legacy Organizations

### ISSUE THREAD

**Issue by arroyoDev** [CrisisCleanup/crisiscleanup#300]
Go to Admin | Legacy Models | Legacy Organizations and then pick an organization and try to edit the name of the org.  it won't save.

**Comment by arroyoDev** [comment]
Here is another symptom with this problem.   I opened up a legacy organization.  changed their name and saved.  This time the save worked.  however, the org is no longer showing up in the UI.  it is correct in the database, but will not display in the list of Legacy Organizations.   Here is an example..   I changed the name of an org to "Texas District - J2e3 Disaster Relief Coalition" and it is now gone.  This link will take you directly to it and it is correct.  https://www.crisiscleanup.org/admin/legacy_organizations/1452/edit

Just now showing up in the UI.

**Comment by tsanders** [comment]
Looking into now.
