### ISSUE TITLE
Government Role

### ISSUE THREAD

**Issue by aarontitus** [CrisisCleanup/crisiscleanup#316]
Create a government role type. Redact data from map, the Edit feature (this might be tricky), and download CSV; disallow claiming.  Basically they get to see:
Address
Lat/Lon
Work Type
Status
Claimed_by
Org. Contact Information
Height of Flood
Probably a few other pieces of data (

eliminate names, phone numbers, notes, details, etc, and limit the data to just what is necessary for situational awareness reporting.

**Comment by arroyoDev** [comment]
Probably add Numer of Volunteer Hours Worked.
