### ISSUE TITLE
General search

### ISSUE THREAD

**Issue by jeromatron** [CrisisCleanup/crisiscleanup#341]
Currently search is only on the map page which is a bit indirect. It would be nice to search for IDs or based on other criteria from the dashboard or an explicit search link.

**Comment by tsanders** [comment]
@jeromatron Yes, totally agree. This is something we would definitely like to add.  In the meantime, users can search for IDs and most other criteria on the "Browse" page (under the "Dashboard" drop-down).

**Comment by jeromatron** [comment]
Thanks for the tip Tyler. And very useful site. Just trying to braindump some thoughts while they're still fresh from working today.

**Comment by tsanders** [comment]
Thanks!  We greatly appreciate the feedback and ideas!  If you or anyone you know is interested in contributing, we welcome that too!
