### ISSUE TITLE
Ability to bookmark places without claiming them or recent view

### ISSUE THREAD

**Issue by jeromatron** [CrisisCleanup/crisiscleanup#342]
I've called several people to verify need and type of work and didn't want to claim them until I did. It would be nice to be able to either bookmark places or have a "recently viewed" ordered by time descending.

**Comment by silvertriclops** [comment]
Agreed this would be very useful. I've just been putting mine in my notes but it can get tedious.

**Comment by tsanders** [comment]
We should be able to add bookmarks easily enough.  We would need to add a separate bookmarks table and corresponding join table. Probably best to have it on the dashboard.  We could add functionality to the dashboard that would allow a user to select what sites show on the left side, currently it's just "claimed worksites".   But some sort of selector could allow the user to filter - "bookmarks", "my claimed sites", "organization sites", and "recently viewed sites".  I think that would keep the interface from getting too cluttered.  There are more things in the works for the dashboard (notifications, stats, etc)
