### ISSUE TITLE
Geolocation for discovering nearby unclaimed sites

### ISSUE THREAD

**Issue by tsanders** [CrisisCleanup/crisiscleanup#344]
Volunteer teams typically go out with worksites already claimed (either viewing the info on the dashboard or a printed workorder).  There are times where plans change and they are looking for new or additional sites to work.  This feature would allow them to quickly find I unworked sites nearby.   Ideally, they would be able to do this on a separate page without having to load the map on a mobile device.  It could just present a list group ordered by proximity.

**Comment by seanfisher** [comment]
+1 We could have used this today, actually
