### ISSUE TITLE
Add contributing.md

### ISSUE THREAD

**Issue by tsanders** [CrisisCleanup/crisiscleanup#345]
Specify background, process (pull requests, CI, staging), tooling, etc

**Comment by jeromatron** [comment]
With a contributing doc do you guys use slack or the github chat feature at all? I often use those for work and community stuff and it's nice to have the realtime communication.

**Comment by arroyoDev** [comment]
We hope to have the contributing do up today. 

We have a slack channel

Crisiscleanup.slack.com

**Comment by jeromatron** [comment]
I just brought it up in the context of possibly adding a link to it in the contributing document.  However currently it requires an invite to join.
