### ISSUE TITLE
Map centers in Pacific ocean when entering address

### ISSUE THREAD

**Issue by TimBanks** [CrisisCleanup/crisiscleanup#354]
In the intake form, when you enter a customer address, the map centers somewhere between Hawaii and Papua New Guinea rather than over the address listed. The pin is in the correct place, but you have you zoom out and scroll over in order to get to the correct address. This nigh impossible on mobile.

<img width="1602" alt="screen shot 2017-09-19 at 3 03 06 pm" src="https://user-images.githubusercontent.com/8888334/30612942-e48e3076-9d4b-11e7-87b6-affef67be9cf.png">

**Comment by arroyoDev** [comment]
does it often... pain in the butt.

**Comment by aarontitus** [comment]
This error only occurs when the user types an address and chooses the Google suggestion. Current work-around is to add a space to one of the address fields (e.g. the Zip Code), then click on a non-address input form. The JS re-loads the map to the correct location.

**Comment by arroyoDev** [comment]
Here is a 1 minute youtube video where they show it happening and how they trick the system to work around it... might be helpful in diagnosing the issue:  https://youtu.be/QLfQ_dDbTUo
