### ISSUE TITLE
Phone Friendly

### ISSUE THREAD

**Issue by arroyoDev** [CrisisCleanup/crisiscleanup#365]
One day may attack the native app idea.  Until that day, there is a lot that can be done to make the site behave as "app" like as possible.    If one or more of you have the mad skills in making this happen, go and make the site AWESOME on a phone.

**Comment by jrahaim** [comment]
As an iOS developer (8 years experience) I am curious if there is any interest/traction on a native client. And if there is an API that would make that easier/possible.

**Comment by arroyoDev** [comment]
Yes and Yes.  

We do have a team working on a phone centric portion of our call center component.  We also have been re-writing the entire system using services.    Are you interested in jumping in and doing some volunteer dev work? 

Ross Arroyo
ross@crisiscleanup.org
601.434.4099
