### ISSUE TITLE
Hide the Legend

### ISSUE THREAD

**Issue by arroyoDev** [CrisisCleanup/crisiscleanup#373]
When using a phone, it is a little annoying
![screen shot 2017-09-20 at 11 34 09 pm](https://user-images.githubusercontent.com/699333/30679061-3e3dc0a8-9e5c-11e7-91f9-f8b1b8c75ef5.jpg)
 to have the legend taking up so much space on the map.  We should make the legend able to slide to the side and slide back in.  

There would need to be enough of a stub out there that you can easily bring it in and out on a small phone screen without too much trouble.

**Comment by deokpyo** [comment]
PR created
https://github.com/CrisisCleanup/crisiscleanup/pull/395
