### ISSUE TITLE
Pull orgs from the database in a way that does not slow down the map

### ISSUE THREAD

**Issue by arroyoDev** [CrisisCleanup/crisiscleanup#379]
This rolling list of Volunteer Organizations is 1000 plus and growing.  I want it to cycle through in random order, but not bog down anything.  right now it is just a few statically loaded.  It needs to pull from the whole is of VERIFIED organizations.   

![screen shot 2017-09-21 at 12 26 37 am](https://user-images.githubusercontent.com/699333/30680190-d60623ba-9e63-11e7-8067-cba60807dcab.jpg)

It's located on the bottom of the map page.

**Comment by TimBanks** [comment]
The easiest way would probably to have it hit a cache backend like redis? Even if you store it in another table, you're going to have contention with it pulling from the database. This would allow the list to be updated with a separate job running every so often and the footprint for the cache should be pretty small.
