### ISSUE TITLE
User Details.  

### ISSUE THREAD

**Issue by arroyoDev** [CrisisCleanup/crisiscleanup#385]
You're going to love this one   https://www.crisiscleanup.org/admin/users

1.  Fix an internal vulnerability where a user can technically edit ALL other users information by simply changing the ID in the Url.   Yeah, I know......   
     https://www.crisiscleanup.org/admin/users/5977/edit    (change 5977 to 1 and see what i mean)  
2.  upgrade the users page with the following information:
    Name
    Mobile number
    email 
    My Organization (as a label) "Change Organizations" button  (see issue #386 )
       ___ List me as a contact for my organization.   (see issue TBD)
Admin checkbox.   Only if you are an admin, do you see the Admin Checkbox.  This now gives yo admin powers.
    
Add deactivate user to this page.  Be sure to pop up a  "Are you sure" message first. see issue #387 

![screen shot 2017-09-21 at 1 27 25 pm](https://user-images.githubusercontent.com/699333/30712161-b0acb0e4-9ed0-11e7-9f79-0b1ce23d9217.jpg)

**Comment by pantherchild** [comment]
Hey crew.

As part of our hackathon today, we have looked at the first part of this issue.  What we've found is that if you're logged in as an admin, you're able to switch between users and update their information at will.  If you're logged in as a regular user, you are not able to switch in the manner described.  Instead, you'll be dropped back to the dashboard page if you attempt to access a page that you don't have the proper permissions to hit.

Assuming that the admin users should be able to access and edit all users, this seems to be the correct behavior.  None of us were able to replicate this behavior with a standard user.

If there's any more information that would help us repro on a standard user, please let us know!

--Jenny

**Comment by arroyoDev** [comment]
Hi Jenny.

Would you mind giving me a call at 601-434-4099?
