### ISSUE TITLE
Phone Bank Overview

### ISSUE THREAD

**Issue by arroyoDev** [CrisisCleanup/crisiscleanup#391]
Currently, phone calls are handled by hundreds of volunteers managing thousands of outbound and inbound calls using 3 separate websites open at the same time

VACD Web Site (Telephone Interface)
http://www.vacd.biz

 Crisis Cleanup (Property/Work Orders)
https://www.crisiscleanup.org

Missed Call Google Spreadsheet (Only if you
are returning calls)
http://bit.ly/2dUWuaG

Here is a PDF with instructions on how they currently do their work.
[Hotline Training-LDS.pdf](https://github.com/CrisisCleanup/crisiscleanup/files/1323039/Hotline.Training-LDS.pdf)

Here is the API for the phone system  VACD.biz  https://portal.vacd.biz/agentui/doc/index.html

You will now be making a module in Crisiscleanup that does it all within the site.   They are going to love it and it will be MUCH simpler.  

![screen shot 2017-09-21 at 5 53 13 pm](https://user-images.githubusercontent.com/699333/30723707-a9c40466-9efe-11e7-95a4-ee108e159431.jpg)

On the user settings page add options 

	Checkbox:  (I am willing to work the call center) 
	Checkbox:   I have completed my phone training
	I will take calls for these states :  Dropdown box
	

If this  both are checked, then show the word “Call” in the top menu bar.

Clicking on the Call link brings you to the Call Screen

The phone number should auto populate from the settings mobile number

The Start Taking Calls button will connect to the API and put them live

Once the go live button is live, it should now Say “Stop Taking Cals” and be a different color.   (API call as well)

You will now have 3 queues:

	Missed Calls
	Needs Special Assistance
	Confirm they still need help

Each queue will have a badge with the count of how many are in the queue
When you touch or click on any one of the 3 it opens, the other two should be collapsed

	Missed Calls
		When a call comes into the hotline and is not answered in time, it then goes to a missed call database somewhere in VACD.biz    use an API call to pull the phone number and populate the missed call list.
        see image
		you will need to match the area code with a new table you sill set up 

		Mach the phone number to our database to see if that number already exists.  You may find zero to many matches.   Zero if that number does not match any case.   otherwise show all the possible matches and expand the box to fit see image… 

		For matches, show the icon and its current color, and the name of the household owner.

The green phone icon will launch the API call to dial the number outbound

The red phone will hang up the call 

		

	Needs Special Assistance

		if the status of Needs special assistance is selected, put them in this queue. 

	Confirm they still need help
		This will load up with with any case number that has not had any activity in X days where X is a setting in admin page  The idea is that you will call the person and see if they still need help.  you will want to update the work order status and remove it form the call list because we now have an update in the system.

**Comment by seanfisher** [comment]
I'll take this one. Don't have permissions to self-assign.
