### ISSUE TITLE
Null value found in Claimed By Field

### ISSUE THREAD

**Issue by arroyoDev** [CrisisCleanup/crisiscleanup#402]
A user discovered this in the field:  

Trevor Christman
Sep 16 11:43 am
 
Hi,

My name is Trevor Christman, and I'm a volunteer helping coordinate Houston flood relief efforts using the Crisis Cleanup website. I had a bug occur while showing something to Aaron Titus and he asked me to send this information to you.

I clicked the item shown in the screenshot when it was unclaimed, and tried to change the status to 'Closed, done by others'. When I did this it came up as claimed by 'null'.

-Trevor Christman

When you look up the order now, it is fine.   

**The goal of this Ticket is to potentially look for how a null value could exist and plug the hole.   Once this search is exhausted or we have a fix, we can retire this bug.**  

![cc_bugreport](https://user-images.githubusercontent.com/699333/30786007-c9664602-a134-11e7-8dd7-81257b1f7b6b.png)

**Comment by quintezkiller** [comment]
I was able to reproduce the bug when changing the status of the Case in the case details section. However, it was saying 'undefined', not 'null'. When clicking 'Edit' and setting the status to 'Closed, (anything here)', it works as expected. What I believe is happening is the Case is being marked as claimed when editing it in the details view.
