### ISSUE TITLE
Call Complete number not displaying next number

### ISSUE THREAD

**Issue by caike** [CrisisCleanup/crisiscleanup#472]
The `Call Complete - Next Call` button on the "Call Dashboard" page is not displaying a new number. 
It displays the green success message at the top, however it does not generate a new number.

(Reporting this from using the production system now)

**Comment by rlgreen91** [comment]
I'd be happy to tackle this one.

**Comment by aarontitus** [comment]
@rlgreen91, thank you so much for your interest. I'm pretty sure that this issue has been resolved. I'll go ahead and close it out.
How did you hear about Crisis Cleanup?
